<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'landing_page' => [[], ['_controller' => 'App\\Controller\\MainController::landingPage'], [], [['text', '/']], [], [], []],
    'get_weather' => [[], ['_controller' => 'App\\Controller\\MainController::getWeather'], [], [['text', '/weather']], [], [], []],
    'get_countries' => [[], ['_controller' => 'App\\Controller\\MainController::getCountries'], [], [['text', '/countries']], [], [], []],
    'about_us' => [[], ['_controller' => 'App\\Controller\\MainController::aboutUs'], [], [['text', '/about-us']], [], [], []],
    'choose_plan' => [[], ['_controller' => 'App\\Controller\\MainController::choosePlan'], [], [['text', '/choose-your-plan']], [], [], []],
];
